---
- name: Restart Tomcat and manage ELB
  hosts: "{{ target_node }}"
  gather_facts: true
  vars:
    region: "{{ lookup('env', 'AWS_REGION') }}"  # Get region from environment
    instance_id: "{{ ansible_ec2_instance_id }}"  # Gathered dynamically
  tasks:
    - name: Remove instance from ELB
      community.aws.elb_instance:
        region: "{{ region }}"
        instance_id: "{{ instance_id }}"
        state: absent
        elb: "{{ elb_name }}"  # Reference the ELB name passed as an extra variable
      register: remove_elb_result

    - name: Wait for 5 minutes before stopping Tomcat
      wait_for:
        timeout: 300  # 5 minutes

    - name: Shutdown Tomcat
      command: /opt/tomcat/bin/shutdown.sh
      ignore_errors: yes

    - name: Kill Java processes if Tomcat shutdown fails
      command: pkill -9 java
      ignore_errors: yes

    - name: Remove files from /opt/server/*
      file:
        path: /opt/server/
        state: absent
      ignore_errors: yes

    - name: Start Tomcat
      command: /opt/tomcat/bin/startup.sh

    - name: Wait for 7 minutes after starting Tomcat
      wait_for:
        timeout: 420  # 7 minutes

    - name: Add instance back to ELB
      community.aws.elb_instance:
        region: "{{ region }}"
        instance_id: "{{ instance_id }}"
        state: present
        elb: "{{ elb_name }}"  # Reference the ELB name passed as an extra variable
      register: add_elb_result